-- Auto-generated by gen_votrax_roms.cpp
-- f1_rom: 128 entries x 18-bit
-- A coefficients (idx 1..N_X, feedforward): scale = 2^22 = 4194304
-- B coefficients (idx 5..7,  feedback):     scale = 2^17 = 131072
-- addr(2:0) = coeff_idx: 0=b0(unused) 1=a0 2=a1 3=a2 4=a3 5=b1 6=b2 7=b3
-- Synchronous read: 1-cycle latency, infers as BRAM

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity f1_rom is
    port (
        clk  : in  std_logic;
        addr : in  unsigned(6 downto 0);
        data : out signed(17 downto 0)
    );
end entity;

architecture rtl of f1_rom is

    -- Scaling constants (for iir_filter_slow generics FP_FRAC_A / FP_FRAC_B)
    constant FP_FRAC_A : integer := 22;  -- A coefficients: scale = 2^22
    constant FP_FRAC_B : integer := 17;  -- B coefficients: scale = 2^17

    type rom_t is array(0 to 127) of signed(17 downto 0);
    constant ROM : rom_t := (
        to_signed(      0, 18),  -- [   0] b0 = +0.000000
        to_signed(   3902, 18),  -- [   1] a0 = +0.000930
        to_signed(   5524, 18),  -- [   2] a1 = +0.001317
        to_signed(   -659, 18),  -- [   3] a2 = -0.000157
        to_signed(  -2281, 18),  -- [   4] a3 = -0.000544
        to_signed(-129782, 18),  -- [   5] b1 = -0.990158
        to_signed(-130971, 18),  -- [   6] b2 = -0.999229
        to_signed( 129883, 18),  -- [   7] b3 = +0.990929
        to_signed(      0, 18),  -- [   8] b0 = +0.000000
        to_signed(   8258, 18),  -- [   9] a0 = +0.001969
        to_signed(  11690, 18),  -- [  10] a1 = +0.002787
        to_signed(  -1395, 18),  -- [  11] a2 = -0.000333
        to_signed(  -4827, 18),  -- [  12] a3 = -0.001151
        to_signed(-129669, 18),  -- [  13] b1 = -0.989296
        to_signed(-130858, 18),  -- [  14] b2 = -0.998367
        to_signed( 129883, 18),  -- [  15] b3 = +0.990929
        to_signed(      0, 18),  -- [  16] b0 = +0.000000
        to_signed(  12410, 18),  -- [  17] a0 = +0.002959
        to_signed(  17567, 18),  -- [  18] a1 = +0.004188
        to_signed(  -2096, 18),  -- [  19] a2 = -0.000500
        to_signed(  -7253, 18),  -- [  20] a3 = -0.001729
        to_signed(-129561, 18),  -- [  21] b1 = -0.988472
        to_signed(-130750, 18),  -- [  22] b2 = -0.997543
        to_signed( 129883, 18),  -- [  23] b3 = +0.990929
        to_signed(      0, 18),  -- [  24] b0 = +0.000000
        to_signed(  16764, 18),  -- [  25] a0 = +0.003997
        to_signed(  23731, 18),  -- [  26] a1 = +0.005658
        to_signed(  -2830, 18),  -- [  27] a2 = -0.000675
        to_signed(  -9797, 18),  -- [  28] a3 = -0.002336
        to_signed(-129448, 18),  -- [  29] b1 = -0.987610
        to_signed(-130637, 18),  -- [  30] b2 = -0.996681
        to_signed( 129884, 18),  -- [  31] b3 = +0.990936
        to_signed(      0, 18),  -- [  32] b0 = +0.000000
        to_signed(  20768, 18),  -- [  33] a0 = +0.004951
        to_signed(  29400, 18),  -- [  34] a1 = +0.007010
        to_signed(  -3505, 18),  -- [  35] a2 = -0.000836
        to_signed( -12137, 18),  -- [  36] a3 = -0.002894
        to_signed(-129344, 18),  -- [  37] b1 = -0.986816
        to_signed(-130533, 18),  -- [  38] b2 = -0.995888
        to_signed( 129884, 18),  -- [  39] b3 = +0.990936
        to_signed(      0, 18),  -- [  40] b0 = +0.000000
        to_signed(  25120, 18),  -- [  41] a0 = +0.005989
        to_signed(  35561, 18),  -- [  42] a1 = +0.008478
        to_signed(  -4239, 18),  -- [  43] a2 = -0.001011
        to_signed( -14679, 18),  -- [  44] a3 = -0.003500
        to_signed(-129231, 18),  -- [  45] b1 = -0.985954
        to_signed(-130419, 18),  -- [  46] b2 = -0.995018
        to_signed( 129884, 18),  -- [  47] b3 = +0.990936
        to_signed(      0, 18),  -- [  48] b0 = +0.000000
        to_signed(  29268, 18),  -- [  49] a0 = +0.006978
        to_signed(  41433, 18),  -- [  50] a1 = +0.009878
        to_signed(  -4937, 18),  -- [  51] a2 = -0.001177
        to_signed( -17102, 18),  -- [  52] a3 = -0.004077
        to_signed(-129124, 18),  -- [  53] b1 = -0.985138
        to_signed(-130312, 18),  -- [  54] b2 = -0.994202
        to_signed( 129884, 18),  -- [  55] b3 = +0.990936
        to_signed(      0, 18),  -- [  56] b0 = +0.000000
        to_signed(  33617, 18),  -- [  57] a0 = +0.008015
        to_signed(  47591, 18),  -- [  58] a1 = +0.011347
        to_signed(  -5669, 18),  -- [  59] a2 = -0.001352
        to_signed( -19643, 18),  -- [  60] a3 = -0.004683
        to_signed(-129011, 18),  -- [  61] b1 = -0.984276
        to_signed(-130199, 18),  -- [  62] b2 = -0.993340
        to_signed( 129884, 18),  -- [  63] b3 = +0.990936
        to_signed(      0, 18),  -- [  64] b0 = +0.000000
        to_signed(  37621, 18),  -- [  65] a0 = +0.008970
        to_signed(  53260, 18),  -- [  66] a1 = +0.012698
        to_signed(  -6343, 18),  -- [  67] a2 = -0.001512
        to_signed( -21982, 18),  -- [  68] a3 = -0.005241
        to_signed(-128907, 18),  -- [  69] b1 = -0.983482
        to_signed(-130095, 18),  -- [  70] b2 = -0.992546
        to_signed( 129884, 18),  -- [  71] b3 = +0.990936
        to_signed(      0, 18),  -- [  72] b0 = +0.000000
        to_signed(  41968, 18),  -- [  73] a0 = +0.010006
        to_signed(  59416, 18),  -- [  74] a1 = +0.014166
        to_signed(  -7074, 18),  -- [  75] a2 = -0.001687
        to_signed( -24521, 18),  -- [  76] a3 = -0.005846
        to_signed(-128794, 18),  -- [  77] b1 = -0.982620
        to_signed(-129982, 18),  -- [  78] b2 = -0.991684
        to_signed( 129885, 18),  -- [  79] b3 = +0.990944
        to_signed(      0, 18),  -- [  80] b0 = +0.000000
        to_signed(  46112, 18),  -- [  81] a0 = +0.010994
        to_signed(  65282, 18),  -- [  82] a1 = +0.015564
        to_signed(  -7770, 18),  -- [  83] a2 = -0.001853
        to_signed( -26941, 18),  -- [  84] a3 = -0.006423
        to_signed(-128687, 18),  -- [  85] b1 = -0.981804
        to_signed(-129874, 18),  -- [  86] b2 = -0.990860
        to_signed( 129885, 18),  -- [  87] b3 = +0.990944
        to_signed(      0, 18),  -- [  88] b0 = +0.000000
        to_signed(  50457, 18),  -- [  89] a0 = +0.012030
        to_signed(  71435, 18),  -- [  90] a1 = +0.017031
        to_signed(  -8500, 18),  -- [  91] a2 = -0.002027
        to_signed( -29479, 18),  -- [  92] a3 = -0.007028
        to_signed(-128574, 18),  -- [  93] b1 = -0.980942
        to_signed(-129761, 18),  -- [  94] b2 = -0.989998
        to_signed( 129885, 18),  -- [  95] b3 = +0.990944
        to_signed(      0, 18),  -- [  96] b0 = +0.000000
        to_signed(  54453, 18),  -- [  97] a0 = +0.012983
        to_signed(  77094, 18),  -- [  98] a1 = +0.018381
        to_signed(  -9171, 18),  -- [  99] a2 = -0.002187
        to_signed( -31812, 18),  -- [ 100] a3 = -0.007585
        to_signed(-128470, 18),  -- [ 101] b1 = -0.980148
        to_signed(-129657, 18),  -- [ 102] b2 = -0.989204
        to_signed( 129885, 18),  -- [ 103] b3 = +0.990944
        to_signed(      0, 18),  -- [ 104] b0 = +0.000000
        to_signed(  58796, 18),  -- [ 105] a0 = +0.014018
        to_signed(  83244, 18),  -- [ 106] a1 = +0.019847
        to_signed(  -9900, 18),  -- [ 107] a2 = -0.002360
        to_signed( -34348, 18),  -- [ 108] a3 = -0.008189
        to_signed(-128357, 18),  -- [ 109] b1 = -0.979286
        to_signed(-129544, 18),  -- [ 110] b2 = -0.988342
        to_signed( 129885, 18),  -- [ 111] b3 = +0.990944
        to_signed(      0, 18),  -- [ 112] b0 = +0.000000
        to_signed(  62935, 18),  -- [ 113] a0 = +0.015005
        to_signed(  89106, 18),  -- [ 114] a1 = +0.021245
        to_signed( -10594, 18),  -- [ 115] a2 = -0.002526
        to_signed( -36765, 18),  -- [ 116] a3 = -0.008765
        to_signed(-128250, 18),  -- [ 117] b1 = -0.978470
        to_signed(-129436, 18),  -- [ 118] b2 = -0.987518
        to_signed( 129885, 18),  -- [ 119] b3 = +0.990944
        to_signed(      0, 18),  -- [ 120] b0 = +0.000000
        to_signed(  67276, 18),  -- [ 121] a0 = +0.016040
        to_signed(  95254, 18),  -- [ 122] a1 = +0.022710
        to_signed( -11321, 18),  -- [ 123] a2 = -0.002699
        to_signed( -39299, 18),  -- [ 124] a3 = -0.009370
        to_signed(-128137, 18),  -- [ 125] b1 = -0.977608
        to_signed(-129323, 18),  -- [ 126] b2 = -0.986656
        to_signed( 129886, 18)   -- [ 127] b3 = +0.990952
    );

begin

    process(clk)
    begin
        if rising_edge(clk) then
            data <= ROM(to_integer(addr));
        end if;
    end process;

end architecture;
