-- Auto-generated by gen_votrax_roms.cpp
-- f3_rom: 128 entries x 18-bit
-- A coefficients (idx 1..N_X, feedforward): scale = 2^19 = 524288
-- B coefficients (idx 5..7,  feedback):     scale = 2^17 = 131072
-- addr(2:0) = coeff_idx: 0=b0(unused) 1=a0 2=a1 3=a2 4=a3 5=b1 6=b2 7=b3
-- Synchronous read: 1-cycle latency, infers as BRAM

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity f3_rom is
    port (
        clk  : in  std_logic;
        addr : in  unsigned(6 downto 0);
        data : out signed(17 downto 0)
    );
end entity;

architecture rtl of f3_rom is

    -- Scaling constants (for iir_filter_slow generics FP_FRAC_A / FP_FRAC_B)
    constant FP_FRAC_A : integer := 19;  -- A coefficients: scale = 2^19
    constant FP_FRAC_B : integer := 17;  -- B coefficients: scale = 2^17

    type rom_t is array(0 to 127) of signed(17 downto 0);
    constant ROM : rom_t := (
        to_signed(      0, 18),  -- [   0] b0 = +0.000000
        to_signed(   5116, 18),  -- [   1] a0 = +0.009758
        to_signed(  15347, 18),  -- [   2] a1 = +0.029272
        to_signed(  15347, 18),  -- [   3] a2 = +0.029272
        to_signed(   5116, 18),  -- [   4] a3 = +0.009758
        to_signed(-122989, 18),  -- [   5] b1 = -0.938332
        to_signed(-125956, 18),  -- [   6] b2 = -0.960968
        to_signed( 128105, 18),  -- [   7] b3 = +0.977364
        to_signed(      0, 18),  -- [   8] b0 = +0.000000
        to_signed(   6453, 18),  -- [   9] a0 = +0.012308
        to_signed(  19359, 18),  -- [  10] a1 = +0.036924
        to_signed(  19359, 18),  -- [  11] a2 = +0.036924
        to_signed(   6453, 18),  -- [  12] a3 = +0.012308
        to_signed(-121657, 18),  -- [  13] b1 = -0.928169
        to_signed(-124619, 18),  -- [  14] b2 = -0.950768
        to_signed( 128110, 18),  -- [  15] b3 = +0.977402
        to_signed(      0, 18),  -- [  16] b0 = +0.000000
        to_signed(   7808, 18),  -- [  17] a0 = +0.014893
        to_signed(  23423, 18),  -- [  18] a1 = +0.044676
        to_signed(  23423, 18),  -- [  19] a2 = +0.044676
        to_signed(   7808, 18),  -- [  20] a3 = +0.014893
        to_signed(-120307, 18),  -- [  21] b1 = -0.917870
        to_signed(-123264, 18),  -- [  22] b2 = -0.940430
        to_signed( 128115, 18),  -- [  23] b3 = +0.977440
        to_signed(      0, 18),  -- [  24] b0 = +0.000000
        to_signed(   9141, 18),  -- [  25] a0 = +0.017435
        to_signed(  27422, 18),  -- [  26] a1 = +0.052303
        to_signed(  27422, 18),  -- [  27] a2 = +0.052303
        to_signed(   9141, 18),  -- [  28] a3 = +0.017435
        to_signed(-118979, 18),  -- [  29] b1 = -0.907738
        to_signed(-121931, 18),  -- [  30] b2 = -0.930260
        to_signed( 128120, 18),  -- [  31] b3 = +0.977478
        to_signed(      0, 18),  -- [  32] b0 = +0.000000
        to_signed(  10542, 18),  -- [  33] a0 = +0.020107
        to_signed(  31627, 18),  -- [  34] a1 = +0.060324
        to_signed(  31627, 18),  -- [  35] a2 = +0.060324
        to_signed(  10542, 18),  -- [  36] a3 = +0.020107
        to_signed(-117583, 18),  -- [  37] b1 = -0.897087
        to_signed(-120530, 18),  -- [  38] b2 = -0.919571
        to_signed( 128125, 18),  -- [  39] b3 = +0.977516
        to_signed(      0, 18),  -- [  40] b0 = +0.000000
        to_signed(  11870, 18),  -- [  41] a0 = +0.022640
        to_signed(  35611, 18),  -- [  42] a1 = +0.067923
        to_signed(  35611, 18),  -- [  43] a2 = +0.067923
        to_signed(  11870, 18),  -- [  44] a3 = +0.022640
        to_signed(-116260, 18),  -- [  45] b1 = -0.886993
        to_signed(-119202, 18),  -- [  46] b2 = -0.909439
        to_signed( 128130, 18),  -- [  47] b3 = +0.977554
        to_signed(      0, 18),  -- [  48] b0 = +0.000000
        to_signed(  13216, 18),  -- [  49] a0 = +0.025208
        to_signed(  39647, 18),  -- [  50] a1 = +0.075621
        to_signed(  39647, 18),  -- [  51] a2 = +0.075621
        to_signed(  13216, 18),  -- [  52] a3 = +0.025208
        to_signed(-114920, 18),  -- [  53] b1 = -0.876770
        to_signed(-117856, 18),  -- [  54] b2 = -0.899170
        to_signed( 128135, 18),  -- [  55] b3 = +0.977592
        to_signed(      0, 18),  -- [  56] b0 = +0.000000
        to_signed(  14539, 18),  -- [  57] a0 = +0.027731
        to_signed(  43618, 18),  -- [  58] a1 = +0.083195
        to_signed(  43618, 18),  -- [  59] a2 = +0.083195
        to_signed(  14539, 18),  -- [  60] a3 = +0.027731
        to_signed(-113601, 18),  -- [  61] b1 = -0.866707
        to_signed(-116533, 18),  -- [  62] b2 = -0.889076
        to_signed( 128141, 18),  -- [  63] b3 = +0.977638
        to_signed(      0, 18),  -- [  64] b0 = +0.000000
        to_signed(  15931, 18),  -- [  65] a0 = +0.030386
        to_signed(  47792, 18),  -- [  66] a1 = +0.091156
        to_signed(  47792, 18),  -- [  67] a2 = +0.091156
        to_signed(  15931, 18),  -- [  68] a3 = +0.030386
        to_signed(-112215, 18),  -- [  69] b1 = -0.856133
        to_signed(-115141, 18),  -- [  70] b2 = -0.878456
        to_signed( 128146, 18),  -- [  71] b3 = +0.977676
        to_signed(      0, 18),  -- [  72] b0 = +0.000000
        to_signed(  17250, 18),  -- [  73] a0 = +0.032902
        to_signed(  51749, 18),  -- [  74] a1 = +0.098703
        to_signed(  51749, 18),  -- [  75] a2 = +0.098703
        to_signed(  17250, 18),  -- [  76] a3 = +0.032902
        to_signed(-110901, 18),  -- [  77] b1 = -0.846107
        to_signed(-113822, 18),  -- [  78] b2 = -0.868393
        to_signed( 128151, 18),  -- [  79] b3 = +0.977715
        to_signed(      0, 18),  -- [  80] b0 = +0.000000
        to_signed(  18586, 18),  -- [  81] a0 = +0.035450
        to_signed(  55758, 18),  -- [  82] a1 = +0.106350
        to_signed(  55758, 18),  -- [  83] a2 = +0.106350
        to_signed(  18586, 18),  -- [  84] a3 = +0.035450
        to_signed(-109570, 18),  -- [  85] b1 = -0.835953
        to_signed(-112486, 18),  -- [  86] b2 = -0.858200
        to_signed( 128156, 18),  -- [  87] b3 = +0.977753
        to_signed(      0, 18),  -- [  88] b0 = +0.000000
        to_signed(  19900, 18),  -- [  89] a0 = +0.037956
        to_signed(  59701, 18),  -- [  90] a1 = +0.113871
        to_signed(  59701, 18),  -- [  91] a2 = +0.113871
        to_signed(  19900, 18),  -- [  92] a3 = +0.037956
        to_signed(-108261, 18),  -- [  93] b1 = -0.825966
        to_signed(-111172, 18),  -- [  94] b2 = -0.848175
        to_signed( 128161, 18),  -- [  95] b3 = +0.977791
        to_signed(      0, 18),  -- [  96] b0 = +0.000000
        to_signed(  21283, 18),  -- [  97] a0 = +0.040594
        to_signed(  63848, 18),  -- [  98] a1 = +0.121780
        to_signed(  63848, 18),  -- [  99] a2 = +0.121780
        to_signed(  21283, 18),  -- [ 100] a3 = +0.040594
        to_signed(-106884, 18),  -- [ 101] b1 = -0.815460
        to_signed(-109789, 18),  -- [ 102] b2 = -0.837624
        to_signed( 128166, 18),  -- [ 103] b3 = +0.977829
        to_signed(      0, 18),  -- [ 104] b0 = +0.000000
        to_signed(  22592, 18),  -- [ 105] a0 = +0.043091
        to_signed(  67777, 18),  -- [ 106] a1 = +0.129274
        to_signed(  67777, 18),  -- [ 107] a2 = +0.129274
        to_signed(  22592, 18),  -- [ 108] a3 = +0.043091
        to_signed(-105579, 18),  -- [ 109] b1 = -0.805504
        to_signed(-108480, 18),  -- [ 110] b2 = -0.827637
        to_signed( 128171, 18),  -- [ 111] b3 = +0.977867
        to_signed(      0, 18),  -- [ 112] b0 = +0.000000
        to_signed(  23919, 18),  -- [ 113] a0 = +0.045622
        to_signed(  71758, 18),  -- [ 114] a1 = +0.136868
        to_signed(  71758, 18),  -- [ 115] a2 = +0.136868
        to_signed(  23919, 18),  -- [ 116] a3 = +0.045622
        to_signed(-104257, 18),  -- [ 117] b1 = -0.795418
        to_signed(-107153, 18),  -- [ 118] b2 = -0.817513
        to_signed( 128177, 18),  -- [ 119] b3 = +0.977913
        to_signed(      0, 18),  -- [ 120] b0 = +0.000000
        to_signed(  25225, 18),  -- [ 121] a0 = +0.048113
        to_signed(  75674, 18),  -- [ 122] a1 = +0.144337
        to_signed(  75674, 18),  -- [ 123] a2 = +0.144337
        to_signed(  25225, 18),  -- [ 124] a3 = +0.048113
        to_signed(-102957, 18),  -- [ 125] b1 = -0.785500
        to_signed(-105847, 18),  -- [ 126] b2 = -0.807549
        to_signed( 128182, 18)   -- [ 127] b3 = +0.977951
    );

begin

    process(clk)
    begin
        if rising_edge(clk) then
            data <= ROM(to_integer(addr));
        end if;
    end process;

end architecture;
