-- Auto-generated by gen_votrax_roms.cpp
-- fx_rom: 8 entries x 18-bit
-- A coefficients (idx 1..N_X, feedforward): scale = 2^18 = 262144
-- B coefficients (idx 5..7,  feedback):     scale = 2^18 = 262144
-- addr(2:0) = coeff_idx: 0=b0(unused) 1=a0 2=a1 3=a2 4=a3 5=b1 6=b2 7=b3
-- Synchronous read: 1-cycle latency, infers as BRAM

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity fx_rom is
    port (
        clk  : in  std_logic;
        addr : in  unsigned(2 downto 0);
        data : out signed(17 downto 0)
    );
end entity;

architecture rtl of fx_rom is

    -- Scaling constants (for iir_filter_slow generics FP_FRAC_A / FP_FRAC_B)
    constant FP_FRAC_A : integer := 18;  -- A coefficients: scale = 2^18
    constant FP_FRAC_B : integer := 18;  -- B coefficients: scale = 2^18

    type rom_t is array(0 to 7) of signed(17 downto 0);
    constant ROM : rom_t := (
        to_signed(      0, 18),  -- [   0] b0 = +0.000000
        to_signed(  65802, 18),  -- [   1] a0 = +0.251015
        to_signed(      0, 18),  -- [   2] a1 = +0.000000
        to_signed(      0, 18),  -- [   3] a2 = +0.000000
        to_signed(      0, 18),  -- [   4] a3 = +0.000000
        to_signed(-130540, 18),  -- [   5] b1 = -0.497971
        to_signed(      0, 18),  -- [   6] b2 = +0.000000
        to_signed(      0, 18)   -- [   7] b3 = +0.000000
    );

begin

    process(clk)
    begin
        if rising_edge(clk) then
            data <= ROM(to_integer(addr));
        end if;
    end process;

end architecture;
