-- sc01_rom.vhd
-- Votrax Phoneme Parameter ROM
-- Auto-generated by rom2vhdl.py
--
-- 64 phonemes x 64-bit entries. Combinatorial (async) read.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity sc01_rom is
    port (
        phoneme : in  std_logic_vector(5 downto 0);
        data    : out std_logic_vector(63 downto 0)
    );
end entity;

architecture rtl of sc01_rom is
begin
    process (phoneme)
        variable i_p : std_logic_vector(7 downto 0);
    begin
        i_p := "00" & phoneme;
        case i_p is
            when x"00" =>
                data <= x"0000036174688127";
            when x"01" =>
                data <= x"01000161D4688127";
            when x"02" =>
                data <= x"020009A1C4688127";
            when x"03" =>
                data <= x"030000E0F0A050A4";
            when x"04" =>
                data <= x"040000FB610316E8";
            when x"05" =>
                data <= x"0500016164C9C1A6";
            when x"06" =>
                data <= x"060007A134C9C1A6";
            when x"07" =>
                data <= x"07000463F3CB546C";
            when x"08" =>
                data <= x"08000161C4E9C1A3";
            when x"09" =>
                data <= x"09000B61806191A6";
            when x"0A" =>
                data <= x"0A000A61906191A6";
            when x"0B" =>
                data <= x"0B0009A1906191A6";
            when x"0C" =>
                data <= x"0C0007A366A58832";
            when x"0D" =>
                data <= x"0D000A61E6241936";
            when x"0E" =>
                data <= x"0E00017390E19122";
            when x"0F" =>
                data <= x"0F000163F7D36428";
            when x"10" =>
                data <= x"10000163FB8B546C";
            when x"11" =>
                data <= x"110009A2FB8B546C";
            when x"12" =>
                data <= x"120001639CD15860";
            when x"13" =>
                data <= x"130008A0706981A3";
            when x"14" =>
                data <= x"140009A0D4084B36";
            when x"15" =>
                data <= x"150008A184E9C1A3";
            when x"16" =>
                data <= x"160007A130498123";
            when x"17" =>
                data <= x"17000A2120498123";
            when x"18" =>
                data <= x"180007A1F409D0A2";
            when x"19" =>
                data <= x"19000A721123642C";
            when x"1A" =>
                data <= x"1A0000E8DB7B342C";
            when x"1B" =>
                data <= x"1B000162FD2204AC";
            when x"1C" =>
                data <= x"1C000173E041C126";
            when x"1D" =>
                data <= x"1D0007A265832CA8";
            when x"1E" =>
                data <= x"1E000B7C00E89126";
            when x"1F" =>
                data <= x"1F000468489132E0";
            when x"20" =>
                data <= x"20000A2184C9C1A6";
            when x"21" =>
                data <= x"210005617069D326";
            when x"22" =>
                data <= x"22000A6164A01226";
            when x"23" =>
                data <= x"230000E354C981A3";
            when x"24" =>
                data <= x"24000CC184E9C1A3";
            when x"25" =>
                data <= x"250007B2631324A8";
            when x"26" =>
                data <= x"26000A2184E8C1A2";
            when x"27" =>
                data <= x"27000A21806191A6";
            when x"28" =>
                data <= x"28000A2180E8C122";
            when x"29" =>
                data <= x"290007A164015326";
            when x"2A" =>
                data <= x"2A000172E81132E0";
            when x"2B" =>
                data <= x"2B00046354084382";
            when x"2C" =>
                data <= x"2C000A207049D326";
            when x"2D" =>
                data <= x"2D000A661460C122";
            when x"2E" =>
                data <= x"2E000A2074E881A7";
            when x"2F" =>
                data <= x"2F0007A074E881A7";
            when x"30" =>
                data <= x"30000461606981A3";
            when x"31" =>
                data <= x"3100016354C981A3";
            when x"32" =>
                data <= x"320007A1E4C981A3";
            when x"33" =>
                data <= x"33000A21B4C981A3";
            when x"34" =>
                data <= x"34000A6134E8C1A2";
            when x"35" =>
                data <= x"350009A180E8C1A2";
            when x"36" =>
                data <= x"36000366106083A2";
            when x"37" =>
                data <= x"3700046190E8C122";
            when x"38" =>
                data <= x"38000A6388E15220";
            when x"39" =>
                data <= x"39000168183800A4";
            when x"3A" =>
                data <= x"3A0008A12448C382";
            when x"3B" =>
                data <= x"3B000A2194688127";
            when x"3C" =>
                data <= x"3C0009A19049D326";
            when x"3D" =>
                data <= x"3D000CC1B06981A3";
            when x"3E" =>
                data <= x"3E000A2300A050A4";
            when x"3F" =>
                data <= x"3F0000F030A058A4";
            when others =>
                data <= (others => '0');
        end case;
    end process;
end architecture;
