-- Auto-generated by gen_votrax_roms.cpp
-- SC01A filter coefficient scale constants
--
-- A coefficients: ROM idx 1..N_X  (feedforward, addr_for_tap: 1+tap)
-- B coefficients: ROM idx 5..4+NB (feedback,    addr_for_tap: 5+(tap-N_X))
-- Scale = 2^FP_FRAC_x  (optimal: largest power of 2 fitting 18-bit signed)

library ieee;
use ieee.std_logic_1164.all;

package sc01a_coeff_scales is

    -- F1
    constant F1_FP_FRAC_A : integer := 22;  -- scale = 4194304
    constant F1_FP_FRAC_B : integer := 17;  -- scale = 131072

    -- F2V
    constant F2V_FP_FRAC_A : integer := 19;  -- scale = 524288
    constant F2V_FP_FRAC_B : integer := 17;  -- scale = 131072

    -- F3
    constant F3_FP_FRAC_A : integer := 19;  -- scale = 524288
    constant F3_FP_FRAC_B : integer := 17;  -- scale = 131072

    -- F4
    constant F4_FP_FRAC_A : integer := 18;  -- scale = 262144
    constant F4_FP_FRAC_B : integer := 17;  -- scale = 131072

    -- FX
    constant FX_FP_FRAC_A : integer := 18;  -- scale = 262144
    constant FX_FP_FRAC_B : integer := 18;  -- scale = 262144

    -- FN
    constant FN_FP_FRAC_A : integer := 31;  -- scale = 2147483648
    constant FN_FP_FRAC_B : integer := 17;  -- scale = 131072

    -- F2N
    constant F2N_FP_FRAC_A : integer := 16;  -- scale = 65536
    constant F2N_FP_FRAC_B : integer := 17;  -- scale = 131072

end package;
